version: 2
registries:
  composer:
    type: composer-repository
    url: https://packages.iamproperty.com/
    username: dependabot
    password: ${{secrets.SATIS_PASSWORD}}
updates:
  - package-ecosystem: composer
    directory: /
    registries:
      - composer
    schedule:
      interval: daily
